# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a051dda39ec9a726b6781e6ad27b6a07f5ebc7d857cfc9ad0444042ca2f469dd8b5ea77490ab0631a346efb89e262bf2aea0f6c0b8349dc567eeb3c78a778b8

test:
  secret_key_base: 1faf21b03059ca14fb71496577f8abd941cef02b80b2bc6ce02cb93a415945749aa07859cab284b8c2bda1772d91db3147f359ef4bf40a122a842b9d945198e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
